### ISSUE TITLE
tokio-runtime-worker-0 panic

### ISSUE THREAD

**Issue by blitztide** [phra/rustbuster#46]
Error:
```
root@kali:~/OSCP/PG/Wombo$ /tmp/rustbuster/target/release/rustbuster dir --url http://192.168.93.69:8080 --wordlist /usr/share/seclists/Discovery/Web-Content/raft-small-files.txt 
~ rustbuster v3.0.3 ~ by phra & ps1dr3x ~

         _     _                 _         _           _        _                 _         _           _           _     
        /\ \  /\_\              / /\      /\ \        / /\     /\_\              / /\      /\ \        /\ \        /\ \   
       /  \ \/ / /         _   / /  \     \_\ \      / /  \   / / /         _   / /  \     \_\ \      /  \ \      /  \ \  
      / /\ \ \ \ \__      /\_\/ / /\ \__  /\__ \    / / /\ \  \ \ \__      /\_\/ / /\ \__  /\__ \    / /\ \ \    / /\ \ \ 
     / / /\ \_\ \___\    / / / / /\ \___\/ /_ \ \  / / /\ \ \  \ \___\    / / / / /\ \___\/ /_ \ \  / / /\ \_\  / / /\ \_\
    / / /_/ / /\__  /   / / /\ \ \ \/___/ / /\ \ \/ / /\ \_\ \  \__  /   / / /\ \ \ \/___/ / /\ \ \/ /_/_ \/_/ / / /_/ / /
   / / /__\/ / / / /   / / /  \ \ \    / / /  \/_/ / /\ \ \___\ / / /   / / /  \ \ \    / / /  \/_/ /____/\   / / /__\/ / 
  / / /_____/ / / /   / / _    \ \ \  / / /     / / /  \ \ \__// / /   / / _    \ \ \  / / /     / /\____\/  / / /_____/  
 / / /\ \ \  / / /___/ / /_/\__/ / / / / /     / / /____\_\ \ / / /___/ / /_/\__/ / / / / /     / / /______ / / /\ \ \    
/ / /  \ \ \/ / /____\/ /\ \/___/ / /_/ /     / / /__________/ / /____\/ /\ \/___/ / /_/ /     / / /_______/ / /  \ \ \   
\/_/    \_\/\/_________/  \_____\/  \_\/      \/_____________\/_________/  \_____\/  \_\/      \/__________\/_/    \_\/   


[?] Started at  : 2021-02-24 12:39:28

thread 'tokio-runtime-worker-0' panicked at 'attempted to leave type `std::mem::ManuallyDrop<internal::SealedBag>` uninitialized, which is invalid', /usr/src/rustc-1.48.0/library/core/src/mem/mod.rs:658:9
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.48.0/library/std/src/panicking.rs:483
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.48.0/library/core/src/panicking.rs:85
   2: core::panicking::panic
             at /usr/src/rustc-1.48.0/library/core/src/panicking.rs:50
   3: std::sync::once::Once::call_once::{{closure}}
   4: std::sync::once::Once::call_inner
             at /usr/src/rustc-1.48.0/library/std/src/sync/once.rs:419
   5: <crossbeam_epoch::default::COLLECTOR as core::ops::deref::Deref>::deref
   6: std::thread::local::fast::Key<T>::try_initialize
   7: tokio_threadpool::worker::Worker::run
   8: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Segmentation fault
```

**Comment by phra** [comment]
it seems that recent toolchains are failing to properly compile rustbuster. i guess that hyper, based on tokio, has to be updated to a more recent version.

**Comment by aress31** [comment]
Same issue there but can't fetch a pre-compiled binary (see #51).

![image](https://user-images.githubusercontent.com/11601622/159375277-a649eca9-f110-420d-9a49-8c950e429fcf.png)

**Comment by prockallsyms** [comment]
Just go to the root of the project and run `cargo update` and then `cargo build`. If you run into any errors post them here, but my build compiled successfully. I am on MacOSX.
